language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
script:
  - yarn lint
  - yarn test --coverage
  - yarn tsc
  - yarn build
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
